#!/bin/bash -l
#PBS -l walltime=96:00:00,nodes=3:ppn=8,mem=80gb
#PBS -m abe
#PBS -M easte080@umn.edu

cd /home/griffint/easte080/blast_diamond_comparison

# useful constants
lowE=0.001
midE=10
highE=200000
BLOCKSIZE=10
NUMPROC=$(nproc --all)
NUMPROC=$(($NUMPROC - 1))

# paths to FASTA query files
fasta_dir=data/rudney_data734ws
fastaAll=$fasta_dir/all.fasta
fastaLess20=$fasta_dir/less20.fasta
fastaGeq20=$fasta_dir/geq20.fasta
fastaLess30=$fasta_dir/less30.fasta
fastaGeq30=$fasta_dir/geq30.fasta
fastaAll=$fasta_dir/short_fasta.fasta
fastaLess30small=$fasta_dir/geq30small.fasta
fastaGeq30small=$fasta_dir/less30small.fasta

# databases
DIAMONDDB=/home/griffint/easte080/nr_db/nr.dmnd
BLASTDB=/home/griffint/easte080/blastdb/nr.blast

# output format
outputFmt="6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qlen"

# path to diamond executable
execDiamond=/home/griffint/easte080/diamond 

# options that don't change in all diamond runs
DIAMOND_CONST_OPTS="-d $DIAMONDDB -b $BLOCKSIZE \
--threads $NUMPROC --outfmt $outputFmt --comp-based-stats 1 --max-target-seqs 100"

BLAST_CONST_OPTS="-db $BLASTDB -max_target_seqs 100 -num_threads $NUMPROC"
 
###--------------- short and long together ----------------------##
# lowest e value
# blast1 
/usr/bin/time -o out/blast1.time -f %e \
	blastp \
	-query "$fastaAll" \
	-matrix PAM30 \
	-evalue $lowE  \
	-out out/blast1.tab \
	$BLAST_CONST_OPTS \
	-outfmt "$outputFmt"


# diamond1: lowest e value, default sens
/usr/bin/time -o out/diamond2.time -f %e \
	$execDiamond blastp\
	-o out/diamond1.tab \
	--matrix PAM30 \
	--evalue $lowE \
	-q $fastaAll \
	$DIAMOND_CONST_OPTS

## diamond2: lowest e, sensitive
echo "Starting diamond2"
/usr/bin/time -o out/diamond2.time -f %e \
	$execDiamond blastp\
	-o out/diamond2.tab \
	--matrix PAM30 \
	--evalue $lowE \
	-q $fastaAll \
	--sensitive \
	$DIAMOND_CONST_OPTS
echo "diamond2 finished"

## diamond3: more sensitivity
echo "starting diamond3"
/usr/bin/time -o out/diamond3.time -f %e \
	$execDiamond blastp\
	-o out/diamond3.tab \
	--matrix PAM30 \
	--evalue $lowE \
	-q $fastaAll \
	--more-sensitive \
	$DIAMOND_CONST_OPTS
echo "diamond3 finished"

### middle e value
### blast2
/usr/bin/time -o out/blast2.time -f %e \
	blastp \
	-query "$fastaAll" \
	-matrix PAM30 \
	-evalue $midE  \
	-out out/blast2.tab \
	$BLAST_CONST_OPTS \
	-outfmt "$outputFmt"

##diamond 4: evalue 10, default sensitivity
/usr/bin/time -o out/diamond4.time -f %e \
	$execDiamond blastp\
	-o out/diamond4.tab \
	--matrix PAM30 \
	--evalue $midE \
	-q $fastaAll \
	$DIAMOND_CONST_OPTS

### diamond5: evalue 10, sensitive
/usr/bin/time -o out/diamond5.time -f %e \
	$execDiamond blastp\
	-o out/diamond5.tab \
	--matrix PAM30 \
	--evalue $midE \
	-q $fastaAll \
	--sensitive \
	$DIAMOND_CONST_OPTS

## diamond6: evalue 10, more sensitivity
/usr/bin/time -o out/diamond6.time -f %e \
	$execDiamond blastp\
	-o out/diamond6.tab \
	--matrix PAM30 \
	--evalue $midE \
	-q $fastaAll \
	--more-sensitive \
	$DIAMOND_CONST_OPTS

### greatest e value
### blast3, greater e value
/usr/bin/time -o out/blast3.time -f %e \
	blastp \
	-query "$fastaAll" \
	-matrix PAM30 \
	-evalue $highE  \
	-out out/blast3.tab \
	$BLAST_CONST_OPTS \
	-outfmt "$outputFmt"

## diamond7: evalue 200000, default sens
/usr/bin/time -o out/diamond7.time -f %e \
	$execDiamond blastp\
	-o out/diamond7.tab \
	--matrix PAM30 \
	--evalue $highE \
	-q $fastaAll \
	$DIAMOND_CONST_OPTS

## diamond8: evalue 200000, sensitive
/usr/bin/time -o out/diamond8.time -f %e \
	$execDiamond blastp\
	-o out/diamond8.tab \
	--matrix PAM30 \
	--evalue $highE \
	-q $fastaAll \
	--sensitive \
	$DIAMOND_CONST_OPTS

## diamond9: evalue 200000, more sensitive
/usr/bin/time -o out/diamond9.time -f %e \
	$execDiamond blastp\
	-o out/diamond9.tab \
	--matrix PAM30 \
	--evalue $highE \
	-q $fastaAll \
	--more-sensitive \
	$DIAMOND_CONST_OPTS

##---------------- short and long separately, less than/greater than 20 aa ------------##
### blast4
/usr/bin/time -o out/blast4.time1 -f %e \
	blastp -task blastp-short \
	-query "$fastaLess20" \
	-matrix PAM30 \
	-evalue "$highE"  \
	-out "out/blast4.tab1" \
	$BLAST_CONST_OPTS \
	-outfmt "$outputFmt" 
/usr/bin/time -o out/blast4.time2 -f %e \
	blastp \
	-query "$fastaGeq20" \
	-matrix BLOSUM62 \
	-evalue "$midE"  \
	-out "out/blast4.tab2" \
	$BLAST_CONST_OPTS \
	-outfmt "$outputFmt"

### diamond 10: default sensitivity
/usr/bin/time -o out/diamond10.time1 -f %e \
	$execDiamond blastp \
	-o out/diamond10.tab1 \
	--matrix PAM30 \
	--evalue $highE \
	-q $fastaLess20 \
	$DIAMOND_CONST_OPTS 
/usr/bin/time -o out/diamond10.time2 -f %e \
	$execDiamond blastp \
	-o out/diamond10.tab2 \
	--matrix BLOSUM62 \
	--evalue $midE \
	-q $fastaGeq20 \
	$DIAMOND_CONST_OPTS 

### diamond 11: sensitive
/usr/bin/time -o out/diamond11.time1 -f %e \
	$execDiamond blastp \
	-o out/diamond11.tab1 \
	--matrix PAM30 \
	--evalue $highE \
	-q $fastaLess20 \
	--sensitive \
	$DIAMOND_CONST_OPTS 
/usr/bin/time -o out/diamond11.time2 -f %e \
	$execDiamond blastp \
	-o out/diamond11.tab2 \
	--matrix BLOSUM62 \
	--evalue $midE \
	-q $fastaGeq20 \
	--sensitive \
	$DIAMOND_CONST_OPTS 

### diamond 12: more sensitive
/usr/bin/time -o out/diamond12.time1 -f %e \
	$execDiamond blastp \
	-o out/diamond15.tab1 \
	--matrix PAM30 \
	--evalue $highE \
	-q $fastaLess20 \
	--more-sensitive \
	$DIAMOND_CONST_OPTS 
/usr/bin/time -o out/diamond12.time2 -f %e \
	$execDiamond blastp \
	-o out/diamond12.tab2 \
	--matrix BLOSUM62 \
	--evalue $midE \
	-q $fastaGeq20 \
	--more-sensitive \
	$DIAMOND_CONST_OPTS 

##---------- short and long separately, lt/geq 30 aa -----------##
### blast5
/usr/bin/time -o out/blast5.time1 -f %e \
	blastp -task blastp-short \
	-query "$fastaLess30" \
	-matrix PAM30 \
	-evalue "$highE"  \
	-out "out/blast5.tab1" \
	$BLAST_CONST_OPTS \
	-outfmt "$outputFmt" 
/usr/bin/time -o out/blast5.time2 -f %e \
	blastp \
	-query "$fastaGeq30" \
	-matrix BLOSUM62 \
	-evalue "$midE"  \
	-out "out/blast5.tab2" \
	$BLAST_CONST_OPTS \
	-outfmt "$outputFmt"

### diamond 13: default sensitivity
/usr/bin/time -o out/diamond13.time1 -f %e \
	$execDiamond blastp \
	-o out/diamond13.tab1 \
	--matrix PAM30 \
	--evalue $highE \
	-q $fastaLess30 \
	$DIAMOND_CONST_OPTS 
/usr/bin/time -o out/diamond13.time2 -f %e \
	$execDiamond blastp \
	-o out/diamond13.tab2 \
	--matrix BLOSUM62 \
	--evalue $midE \
	-q $fastaGeq30 \
	$DIAMOND_CONST_OPTS 

### diamond 14: sensitive
/usr/bin/time -o out/diamond14.time1 -f %e \
	$execDiamond blastp \
	-o out/diamond14.tab1 \
	--matrix PAM30 \
	--evalue $highE \
	-q $fastaLess30 \
	--sensitive \
	$DIAMOND_CONST_OPTS 
/usr/bin/time -o out/diamond14.time2 -f %e \
	$execDiamond blastp \
	-o out/diamond14.tab2 \
	--matrix BLOSUM62 \
	--evalue $midE \
	-q $fastaGeq30 \
	--sensitive \
	$DIAMOND_CONST_OPTS 

### diamond 15: more sensitive
/usr/bin/time -o out/diamond15.time1 -f %e \
	$execDiamond blastp \
	-o out/diamond15.tab1 \
	--matrix PAM30 \
	--evalue $highE \
	-q $fastaLess30 \
	--more-sensitive \
	$DIAMOND_CONST_OPTS 
/usr/bin/time -o out/diamond15.time2 -f %e \
	$execDiamond blastp \
	-o out/diamond15.tab2 \
	--matrix BLOSUM62 \
	--evalue $midE \
	-q $fastaGeq30 \
	--more-sensitive \
	$DIAMOND_CONST_OPTS 
